import React, { useState } from 'react';
import { PlatformPage } from '../../types';
import { ApiSubmission } from '../../api/client';
import { CurrentRound, formatDeadline } from '../../lib/round';
import { beatmapUrl, REVIEW_PRESENTATION, toBeatmap } from '../../lib/submission';
import { BeatmapCardPlatform } from './BeatmapCardPlatform';
import { WithdrawButton } from './WithdrawButton';
import { ChevronRight, CheckCircle2, Link as LinkIcon, RefreshCw, Upload } from 'lucide-react';

function Stat({ label, value, tone }: { label: string; value: string; tone: string }) {
  return <div className="bg-slate-900/60 border border-slate-800/60 rounded-xl px-4 py-2.5 text-right min-w-[7.5rem]"><div className="text-[10px] text-slate-600 uppercase tracking-wider mb-0.5">{label}</div><div className={`text-lg font-black font-mono ${tone}`}>{value}</div></div>;
}

export function SubmissionStatusBand({ round, approvedCount, countdown }: { round: CurrentRound; approvedCount: number; countdown: string }) {
  return <div className="bg-[#0d1526] border border-amber-400/20 rounded-2xl p-5"><div className="flex items-start justify-between gap-6 flex-wrap"><div><div className="flex items-center gap-2 mb-1.5"><div className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse flex-shrink-0" /><h2 className="text-lg font-black text-white">Round {round.roundNumber} — Submissions Open</h2></div><p className="text-xs text-slate-500">Closes {formatDeadline(round.schedule.submission)}</p></div><div className="flex items-center gap-3 flex-wrap"><Stat label="Closes in" value={countdown} tone="text-amber-400" /><Stat label="Approved for voting" value={String(approvedCount)} tone="text-white" /></div></div><p className="text-[11px] text-slate-600 mt-4 leading-relaxed">Entries stay private while submissions are open — only the number already approved is shown, so nobody&apos;s pick is swayed by what is in already.</p></div>;
}

export function YourSubmission({ submission, onWithdraw, onNavigate }: { submission: ApiSubmission | null; onWithdraw: (submissionId: number) => Promise<string | null>; onNavigate: (page: PlatformPage) => void }) {
  const copy = submission ? REVIEW_PRESENTATION[submission.reviewStatus] : null;
  return <section><p className="text-[10px] uppercase tracking-widest text-slate-600 font-mono mb-1">This round</p><h2 className="text-xl font-black text-white mb-5">Your Submission</h2>{submission && copy ? <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,22rem)_1fr] gap-5 items-start"><BeatmapCardPlatform beatmap={toBeatmap(submission)} /><div className="bg-[#0d1526] border border-slate-800 rounded-2xl p-5 space-y-4"><div><span className={`inline-block text-[11px] font-black uppercase tracking-wider px-3 py-1 rounded-full border ${copy.tone}`}>{copy.label}</span><p className="text-xs text-slate-500 mt-3 leading-relaxed">{copy.blurb}</p></div><div className="h-px bg-slate-800" /><div><p className="text-[10px] uppercase tracking-widest text-slate-600 font-mono mb-2">Challenge requirements</p><div className="flex items-center gap-2 flex-wrap"><span className="text-sm font-black font-mono bg-slate-800 border border-slate-700 px-3 py-1 rounded-lg text-white">{submission.modRequirement}</span><span className="text-sm font-bold bg-amber-400/10 border border-amber-400/25 px-3 py-1 rounded-lg text-amber-400">{submission.challengeRequirement}</span></div></div><a href={beatmapUrl(submission)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs text-slate-500 hover:text-amber-400 transition-colors"><LinkIcon className="w-3.5 h-3.5" />Open on osu!</a><WithdrawButton submissionId={submission.id} onWithdraw={onWithdraw} /></div></div> : <div className="bg-[#0d1526] border border-slate-800 rounded-2xl px-6 py-10 text-center"><div className="w-14 h-14 rounded-full bg-slate-900 border border-slate-800 flex items-center justify-center mx-auto mb-4"><Upload className="w-6 h-6 text-slate-700" /></div><p className="text-white font-bold mb-1">You haven&apos;t submitted a beatmap yet</p><p className="text-sm text-slate-500 mb-5 max-w-md mx-auto">One submission per player per round. Pick a Ranked, Loved or Approved difficulty and set the mod and challenge it should be played under.</p><button type="button" onClick={() => onNavigate('submit')} className="inline-flex items-center gap-2 px-6 py-2.5 bg-amber-400 hover:bg-amber-300 text-slate-950 font-black text-sm rounded-xl transition-all"><Upload className="w-4 h-4" />Submit a Beatmap</button></div>}</section>;
}

export function SubmissionRequirements({ onNavigate }: { onNavigate: (page: PlatformPage) => void }) {
  const rules = ['Ranked, Loved or Approved beatmap', 'A specific difficulty, not just the beatmapset', 'One submission per player per round', 'An osu! account eligible to submit'];
  return <div className="bg-[#0d1526] border border-slate-800 rounded-2xl p-5"><div className="flex items-center justify-between gap-4 mb-4 flex-wrap"><div className="flex items-center gap-2.5"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><h3 className="text-sm font-black text-white">Submission Requirements</h3></div><button type="button" onClick={() => onNavigate('submit')} className="flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-amber-400 transition-colors">Full requirements<ChevronRight className="w-3.5 h-3.5" /></button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">{rules.map((rule) => <div key={rule} className="flex items-start gap-2.5"><CheckCircle2 className="w-3.5 h-3.5 text-emerald-400/70 flex-shrink-0 mt-0.5" /><span className="text-xs text-slate-400 leading-relaxed">{rule}</span></div>)}</div></div>;
}

export function ImportFavoritesButton({ onImport, disabled }: { onImport: () => Promise<string | null>; disabled?: boolean }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [failed, setFailed] = useState(false);
  const run = async () => { setBusy(true); setMessage(null); const error = await onImport(); setBusy(false); setFailed(error !== null); setMessage(error ?? 'Imported your osu! favourites.'); };
  return <div className="flex flex-col items-end gap-1"><button type="button" onClick={() => void run()} disabled={busy || disabled} title={disabled ? 'Log in to import your osu! favourites' : undefined} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 hover:border-slate-700 disabled:opacity-40 disabled:cursor-not-allowed text-slate-400 hover:text-white text-xs font-bold transition-all"><RefreshCw className={`w-3.5 h-3.5 ${busy ? 'animate-spin' : ''}`} />{busy ? 'Importing…' : 'Load my osu! favorites'}</button>{message && <p className={`text-[10px] ${failed ? 'text-rose-400/90' : 'text-slate-500'}`}>{message}</p>}</div>;
}
